import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: "#f0f0f0",
      paddingHorizontal: 19,
      paddingVertical: 35,
    },
    topbar: {
      height: 80,
      width: "100%",
      backgroundColor: "#f0f0f0",
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    notifbar: {
      height: 50,
      width: 50,
      backgroundColor: "#f0f0f0",
      alignItems: "center",
      justifyContent: "center",
    },
    bar: {
      height: 80,
      width: 200,
      justifyContent: "center",
      alignItems: "flex-start",
      marginBottom: 10,
      paddingLeft: 8,
    },
    selamat: {
      fontSize: 22,
      // fontWeight: "bold",
      color: "#f4a84f",
      fontFamily: "PoppinsSemiBold"
    },
    booster: {
      fontSize: 22,
      fontWeight: "bold",
      color: "#1a4756",
    },
    secondbar: {
      height: 150,
      width: "100%",
      backgroundColor: "#1a4756",
      marginTop: 3,
      borderRadius: 30,
      flexDirection: "row",
      shadowColor: "#000",
      shadowOffset: {
        width: 0,
        height: 9,
      },
      shadowOpacity: 0.5,
      shadowRadius: 12.35,
      elevation: 19,
    },
    date: {
      height: 150,
      width: 180,
      borderRadius: 50,
      backgroundColor: "#1a4756",
    },
    hari: {
      fontSize: 17,
      fontWeight: "500",
      marginLeft: 20,
      marginTop: 20,
      color: "#f0f0f0",
    },
    tgl: {
      fontSize: 17,
      fontWeight: "500",
      marginLeft: 20,
      color: "#f0f0f0",
    },
    boxbutton1: {
      height: 150,
      width: 142,
      backgroundColor: "#1a4756",
      borderRadius: 50,
      justifyContent: "flex-end",
      alignItems: "center",
      padding: 15,
      marginLeft: 30,
    },
    button1: {
      height: 35,
      width: 100,
      backgroundColor: "#f4a84f",
      borderRadius: 20,
      justifyContent: "center",
      alignItems: "center",
      shadowColor: "#000000",
      shadowOffset: {
        width: 0,
        height: 6,
      },
      shadowOpacity: 0.2,
      shadowRadius: 5.62,
      elevation: 8,
    },
    history: {
      fontSize: 15,
      fontWeight: "bold",
      color: "#1a4756",
    },
    input: {
      height: 50,
      width: "100%",
      marginTop: 20,
      borderRadius: 20,
      borderColor: "000",
      borderWidth: 1,
    },
    bottombar: {
      height: 440,
      width: "100%",
      backgroundColor: "#1a4756",
      marginTop: 20,
      borderRadius: 30,
      padding: 20,
      justifyContent: "space-evenly",
      alignItems: "center",
    },
    baratas: {
      height: 45,
      width: 280,
      backgroundColor: "#f4a84f",
      justifyContent: "center",
      alignItems: "center",
      borderRadius: 20,
      shadowColor: "#000000",
      shadowOffset: {
        width: 0,
        height: 6,
      },
      shadowOpacity: 0.2,
      shadowRadius: 5.62,
      elevation: 8,
    },
    teksput: {
      fontSize: 17,
      color: "#1a4756",
      fontWeight: "bold",
    },
    mulai: {
      height: 45,
      width: "100%",
      backgroundColor: "#f4a84f",
      borderRadius: 20,
      justifyContent: "center",
      alignItems: "center",
      shadowColor: "#000000",
      shadowOffset: {
        width: 0,
        height: 6,
      },
      shadowOpacity: 0.2,
      shadowRadius: 5.62,
      elevation: 8,
    },
    teksmulai: {
      fontSize: 17,
      fontWeight: "bold",
      color: "#1a4756",
    },
    bartengah: {
      height: 320,
      width: 280,
      backgroundColor: "#1a4756",
      flexDirection: "column",
      borderRadius: 20,
    },
    waktu: {
      height: 115,
      width: 250,
      backgroundColor: "#f4a84f",
      borderRadius: 20,
      marginTop: 9,
      flexDirection: "row",
      marginBottom: 3,
      shadowColor: "#000000",
      shadowOffset: {
        width: 0,
        height: 6,
      },
      shadowOpacity: 0.2,
      shadowRadius: 5.62,
      elevation: 8,
    },
    timef: {
      fontSize: 17,
      color: "#1a4756",
      fontWeight: "bold",
    },
    waktujam: {
      fontSize: 17,
      color: "#1a4756",
      fontWeight: "bold",
      marginTop: 5,
    },
    sa: {
      height: 160,
      width: 300,
      backgroundColor: "#1a4756",
      flexDirection: "row",
      alignItems: "center",
      borderRadius: 20,
      marginBottom: 2,
    },
    dalamwaktu1: {
      height: 115,
      width: 220,
      backgroundColor: "#f4a84f",
      borderRadius: 20,
      padding: 10,
    },
    dalamwaktu2: {
      height: 115,
      width: 60,
      backgroundColor: "#f4a84f",
      borderRadius: 20,
      padding: 10,
      flexDirection: "row-reverse",
      justifyContent: "space-between",
    },
    tt: {
      height: 30,
      width: 30,
      backgroundColor: "#f4a84f",
    },
    suhu: {
      height: 130,
      width: 125,
      backgroundColor: "#f4a84f",
      borderRadius: 20,
      marginRight: 25,
      justifyContent: "flex-start",
      shadowColor: "#000000",
      shadowOffset: {
        width: 0,
        height: 6,
      },
      shadowOpacity: 0.2,
      shadowRadius: 5.62,
      elevation: 8,
    },
    alkohol: {
      height: 130,
      width: 125,
      backgroundColor: "#f4a84f",
      borderRadius: 20,
      flexDirection: "row",
      shadowColor: "#000000",
      shadowOffset: {
        width: 0,
        height: 6,
      },
      shadowOpacity: 0.2,
      shadowRadius: 5.62,
      elevation: 8,
    },
    boxsuhu: {
      height: 60,
      width: 125,
      backgroundColor: "#f4a84f",
      borderRadius: 20,
      padding: 10,
      flexDirection: "row",
      justifyContent: "space-between",
    },
    textsuhu: {
      fontSize: 15,
      fontWeight: "bold",
      color: "#1a4756",
    },
    boxsuhu2: {
      height: 60,
      width: 125,
      backgroundColor: "#f4a84f",
      justifyContent: "flex-end",
      padding: 10,
      marginTop: 10,
      borderRadius: 20,
    },
    derjat: {
      fontSize: 25,
      fontWeight: "bold",
      color: "#1a4756",
    },
    boxalkohol: {
      height: 60,
      width: 75,
      backgroundColor: "#f4a84f",
      padding: 10,
      borderRadius: 20,
    },
    ikonalkohol: {
      height: 70,
      width: 48,
      backgroundColor: "#f4a84f",
      padding: 10,
      borderRadius: 20,
      marginLeft: 2,
    },
  });

  export default styles;